export const data = [
  {
    job_id: "phM_HyZLHwm6hBTmAAAAAA==",
    employer_name: "Keysight Technologies, Inc.",
    employer_logo:
      "https://www.keysight.com/content/dam/keysight/en/img/gnav/keysight-logo.svg",
    employer_website: "http://www.keysight.com",
    employer_company_type: "Manufacturing",
    job_publisher: "Keysight Technologies",
    job_employment_type: "FULLTIME",
    job_title: "R&D Engineer 5, Hardware",
    job_apply_link: "https://jobs.keysight.com/jobs/27152?lang=en-us",
    job_apply_is_direct: true,
    job_apply_quality_score: 0.7903,
    apply_options: [
      {
        publisher: "Keysight Technologies",
        apply_link: "https://jobs.keysight.com/jobs/27152?lang=en-us",
        is_direct: true,
      },
      {
        publisher: "Talent.com:求人検索",
        apply_link: "https://jp.talent.com/view?id=6eb3f58db35e",
        is_direct: false,
      },
      {
        publisher: "Expertini | Japan Jobs Expertini",
        apply_link:
          "https://jp.expertini.com/jobs/job/r-d-engineer-5-hardware-hachioji-keysight-technologie-6eb3f58db3/",
        is_direct: false,
      },
    ],
    job_description:
      "Overview\n\nKeysight is on the forefront of technology innovation, delivering breakthroughs and trusted insights in electronic design, simulation, prototyping, test, manufacturing, and optimization. Our ~15,000 employees create world-class solutions in communications, 5G, automotive, energy, quantum, aerospace, defense, and semiconductor markets for customers in over 100 countries. Learn more about what we do.\n\nOur powerful, award-winning culture embraces a bold vision of where technology can take us and a passion for tackling challenging problems with industry-first solutions. Diversity, equity & inclusion are integral parts of our culture and drivers of innovation at Keysight. We believe that when people feel a sense of belonging, they can be more creative, innovative, and thrive at all points in their careers.\n\nResponsibilities\n\nThis job is in Wafer Test Solutions (WTS) team where we research, design, develop and manufacture the world’s most advanced semiconductor wafer and chip test solutions used to evaluate chip design, to control manufacturing process, or to verify performance and functions of semiconductor products. Your work will advance the state of the art of chip industry – supporting high-end smartphones, data centers, AI, autonomous vehicles, IoT and many other fields where semiconductor is key enabling component.\n\nIn this role as a System Design Engineer you will be a key member of a multidisciplinary and international team of R&D engineers who research and develop wafer test systems with Keysight's high-end instruments, advanced mechanical integration and platform software controlling complex test workflows. You will bring the solution research and design from initial concept to final product realization, implement agile development process and interact with global customers to solve their challenges at our local world class factory right here in Hachioji, Japan.\n\nQualifications\n\nBachelors or Masters Degree or University Degree or equivalent. Typically 8+ year’s relevant experience for entry to this level. Post-graduate and/or certification/ license may be required. Requires in-depth knowledge and experience in job and ability to work independently.\n\nCareers Privacy Statement\n• **Keysight is an Equal Opportunity Employer.***",
    job_is_remote: false,
    job_posted_at_timestamp: 1713888000,
    job_posted_at_datetime_utc: "2024-04-23T16:00:00.000Z",
    job_city: "八王子市",
    job_state: null,
    job_country: "JP",
    job_latitude: 35.66644,
    job_longitude: 139.31601,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=japan&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=japan&htidocid=phM_HyZLHwm6hBTmAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2025-04-24T01:23:53.000Z",
    job_offer_expiration_timestamp: 1745457833,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 96,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: ["UNAVAILABLE"],
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: true,
      degree_preferred: false,
      professional_certification_mentioned: true,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {},
    job_job_title: "R&d engineer",
    job_posting_language: "en",
    job_onet_soc: "17206100",
    job_onet_job_zone: "4",
    job_occupational_categories: null,
    job_naics_code: "334513",
    job_naics_name:
      "Instruments and Related Products Manufacturing for Measuring, Displaying, and Controlling Industrial Process Variables",
  },
  {
    job_id: "a6l6k6bQUImXvI6CAAAAAA==",
    employer_name: "OpenAI",
    employer_logo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/OpenAI_Logo_%282%29.svg/2560px-OpenAI_Logo_%282%29.svg.png",
    employer_website: "http://openai.com",
    employer_company_type: "Information",
    job_publisher: "Startup Jobs",
    job_employment_type: "FULLTIME",
    job_title: "Regional Marketing, Japan",
    job_apply_link:
      "https://startup.jobs/regional-marketing-japan-openai-5414504",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5225,
    apply_options: [
      {
        publisher: "Startup Jobs",
        apply_link:
          "https://startup.jobs/regional-marketing-japan-openai-5414504",
        is_direct: false,
      },
      {
        publisher: "The Rundown Jobs - The Rundown AI",
        apply_link:
          "https://jobs.therundown.ai/jobs/57778803-regional-marketing-japan",
        is_direct: false,
      },
      {
        publisher: "The AI Job Network",
        apply_link:
          "https://aijobnetwork.com/jobs/openai-regional-marketing-japan",
        is_direct: false,
      },
      {
        publisher: "AI Nudge Jobs",
        apply_link:
          "https://www.ainudgejobs.com/jobs/57776360-regional-marketing-japan",
        is_direct: false,
      },
    ],
    job_description:
      "About the Team\n\nLike every team at OpenAI, the Marketing team contributes to our broader mission of ensuring responsible and widespread adoption of artificial intelligence. With that aim in mind, we are responsible for developing and executing strategies that drive awareness, engagement, and usage for OpenAI’s products and platform amongst our core audiences. We take a data-driven approach to understand our customers' needs and challenges, ensuring that their voices are reflected in product development and messaging. We then partner closely with product, engineering, developer relations, comms, and sales teams to create a cohesive customer experience across all our channels. Our focus extends beyond just promoting product features; we aim to provide valuable insights and resources that help our users make the most out of AI technologies.\n\nAbout the Role\n\nAs the first marketing hire in Asia, this role will establish our marketing practices in the region with a strong focus on Japan and a few other strategic markets as needed. You'll be essential in developing and executing our marketing plans to establish OpenAI's presence in the region. You'll collaborate with teams across the company to deliver effective marketing initiatives, including the rest of our marketing team, Comms & PR, sales, design, and more.\n\nThe role demands a unique blend of strategic foresight and practical execution skills. You'll need to thrive in fast-paced environments, adapting swiftly to the dynamics of the AI technology landscape. A deep enthusiasm for marketing and a drive to explore new technologies are essential for success in this role. We’re also looking for someone to champion the needs of audiences in the region back to the rest of the organization.\n\nThis role is based in Tokyo, Japan. We use a hybrid work model of 3 days in the office per week and offer relocation assistance to new employees.\n\nIn this role, you will:\n\n• Develop a comprehensive marketing strategy for the Japanese market, including conducting market and competitor research, defining goals & workstreams in collaboration with the global Marketing team and local leadership.\n\n• Plan consumer campaigns and manage creative targeted at increasing awareness and adoption for ChatGPT.\n• Identify key customer segments for sales-led buyer journeys and align with cross-functional stakeholders, such as sales leaders to execute demand generation campaigns and handoffs.\n• Produce quality content in bilingual format, such as web pages, case studies, newsletters, etc.\n• Leverage third-party and first-party event channels, including online webinars; identify co-marketing opportunities with third parties as the Japan footprint grows.\n\n• Build an effective local team in Japan and beyond to high-priority Asia markets, including onboarding creative/advertising agencies and hiring a few core team members (as needed).\n\n• Collaborate with Sales, Comms, Product, Legal, and other cross-functional teams to establish a strong credibility and well-perceived presence in Japan and priority Asia markets.\n• Share best practices and insights from the region to other markets.\n\nYou might thrive in this role if you:\n\n• Have 7+ years of experience in marketing leadership in Asia, ideally in Japan.\n• Native-level Japanese language proficiency.\n• Strong track record of leading marketing strategy development and driving multi-channel campaigns.\n• Are a strong communicator, able to effectively articulate insights and recommendations to both technical and non-technical audiences.\n• Can flex between consumer and B2B audiences.\n• Are proactive, detail-oriented, and capable of managing multiple projects simultaneously in a fast-paced environment.\n• Share a passion for AI and its potential to transform industries and society.\n\nAbout OpenAI\n\nOpenAI is an AI research and deployment company dedicated to ensuring that general-purpose artificial intelligence benefits all of humanity. We push the boundaries of the capabilities of AI systems and seek to safely deploy them to the world through our products. AI is an extremely powerful tool that must be created with safety and human needs at its core, and to achieve our mission, we must encompass and value the many different perspectives, voices, and experiences that form the full spectrum of humanity.\n\nWe are an equal opportunity employer and do not discriminate on the basis of race, religion, national origin, gender, sexual orientation, age, veteran status, disability or any other legally protected status.\n\nFor US Based Candidates: Pursuant to the San Francisco Fair Chance Ordinance, we will consider qualified applicants with arrest and conviction records.\n\nWe are committed to providing reasonable accommodations to applicants with disabilities, and requests can be made via this link.\n\nOpenAI Global Applicant Privacy Policy\n\nAt OpenAI, we believe artificial intelligence has the potential to help people solve immense global challenges, and we want the upside of AI to be widely shared. Join us in shaping the future of technology.",
    job_is_remote: false,
    job_posted_at_timestamp: 1713868111,
    job_posted_at_datetime_utc: "2024-04-23T10:28:31.000Z",
    job_city: null,
    job_state: null,
    job_country: "JP",
    job_latitude: 35.676422,
    job_longitude: 139.65002,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=japan&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=japan&htidocid=a6l6k6bQUImXvI6CAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 84,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {},
    job_job_title: "Regional marketing",
    job_posting_language: "en",
    job_onet_soc: "13116100",
    job_onet_job_zone: "4",
    job_occupational_categories: [
      "15-1132.00 Software Developers, Application",
    ],
    job_naics_code: "511",
    job_naics_name: "Publishing Industries (except Internet)",
  },
  {
    job_id: "jpXoWPMkracWtmsqAAAAAA==",
    employer_name: "300-SFDC Japan",
    employer_logo: null,
    employer_website: null,
    employer_company_type: null,
    job_publisher: "Workday",
    job_employment_type: "FULLTIME",
    job_title: "Strategy Analyst",
    job_apply_link:
      "https://salesforce.wd12.myworkdayjobs.com/en-US/External_Career_Site/job/Japan---Tokyo/Strategy-Analyst_JR249319",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.7834,
    apply_options: [
      {
        publisher: "Workday",
        apply_link:
          "https://salesforce.wd12.myworkdayjobs.com/en-US/External_Career_Site/job/Japan---Tokyo/Strategy-Analyst_JR249319",
        is_direct: false,
      },
    ],
    job_description:
      "To get the best candidate experience, please consider applying for a maximum of 3 roles within 12 months to ensure you are not duplicating efforts. Job Category Operations Job Details About Salesforce We’re Salesforce, the Customer Company, inspiring the future of business with AI+ Data +CRM. Leading with our core values, we help companies across every industry blaze new trails and connect with customers in a whole new way. And, we empower you to be a Trailblazer, too — driving your performance and career growth, charting new paths, and improving the state of the world. If you believe in business as the greatest platform for change and in companies doing well and doing good – you’ve come to the right place. The Analyst will be joining our Quota and Capacity Planning team, where they will partner with a variety of departments to support the Japan Sales and Strategy & Operations team through the company’s annual quota planning cycle and throughout the year as the organization changes. This position will require developing a broad understanding of many policies, processes, and technologies used to support the business. As a Quota & Capacity Planning team, we accelerate global ACV by delivering accurate, reliable quotas on time during both Fast Start as well as throughout the fiscal year. We operate with the guiding principles: Salesforce First, Reliability, Partnership, and Respect. The ideal candidate is a curious, driven, self-starter who enjoys working in dynamic, fast-paced environments and is experienced in working in conditions where priorities change rapidly and require seamless pivoting to new projects. Responsibilities Advise the Japan strategy team as to the impact of go-to-market decisions, processes, and policies on sales team quotas during the company’s annual planning cycle Develop and own concurrent data reporting projects and models to help drive insights for the regional strategy teams, based on an intimate knowledge of your support area Partner with multiple stakeholders across different countries and timezones including Sales, Sales Strategy, Finance, Sales Compensation, and Employee Success Assist with project leading Japan’s annual fiscal year quota planning process end-to-end Process and maintain quotas for Japan’s sales teams and sales leaders once the annual planning cycle is completed Assist the Quota and Capacity Planning team in APAC quota-related maintenance, tasks, and projects where required Required skills & Experience English language speaking proficiency is required to work with stakeholders based outside of Japan 3+ years of work experience, ideally in Sales Operations, Sales Strategy, FP&A or Compensation where business analysis and insights was in the DNA Ability to work both independently and with a team. Comfortable with reporting to global managers and stakeholders outside Japan Power-user proficiency in Google-sheets and ability to tell a story in Google-slides Proven analytical and problem-solving skills, along with attention to detail Ability to establish and build close working relationships. Strong personal credibility and counseling skills. Desired Skills & Experience Experience with sales coverage models, quota setting methodologies, territory alignment and compensation policies Ability to succeed in a collaborative, start-up paced environment which may include extended time commitments during busy-season Capable to work well under deadlines and juggle multiple priorities. Strong meeting management skills. Experience using Anaplan, Salesforce, Tableau, Slack or SQL Accommodations If you require assistance due to a disability applying for open positions please submit a request via this Accommodations Request Form. Posting Statement At Salesforce we believe that the business of business is to improve the state of our world. Each of us has a responsibility to drive Equality in our communities and workplaces. We are committed to creating a workforce that reflects society through inclusive programs and initiatives such as equal pay, employee resource groups, inclusive benefits, and more. Learn more about Equality at www.equality.com and explore our company benefits at www.salesforcebenefits.com. Salesforce is an Equal Employment Opportunity and Affirmative Action Employer. Qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender perception or identity, national origin, age, marital status, protected veteran status, or disability status. Salesforce does not accept unsolicited headhunter and agency resumes. Salesforce will not pay any third-party agency or company that does not have a signed agreement with Salesforce. ﻿Salesforce welcomes all. We're Salesforce, the Customer Company, inspiring the future of business with AI + Data + CRM. Leading with our core values, we help companies across every industry blaze new trails and connect with customers in a whole new way. And, we empower you to be a Trailblazer, too — driving your performance and career growth, charting new paths, and improving the state of the world. If you believe in business as the greatest platform for change and in companies doing well and doing good – you've come to the right place.",
    job_is_remote: true,
    job_posted_at_timestamp: 1713916800,
    job_posted_at_datetime_utc: "2024-04-24T00:00:00.000Z",
    job_city: null,
    job_state: null,
    job_country: "JP",
    job_latitude: 36.204823,
    job_longitude: 138.25293,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=japan&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=japan&htidocid=jpXoWPMkracWtmsqAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 36,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {},
    job_job_title: "Strategy analyst",
    job_posting_language: "en",
    job_onet_soc: "13111100",
    job_onet_job_zone: "5",
    job_occupational_categories: null,
    job_naics_code: null,
    job_naics_name: null,
  },
  {
    job_id: "FSs0aq4qCHSmKmm_AAAAAA==",
    employer_name: "Bank of America",
    employer_logo:
      "https://www.bankofamerica.com/content/images/ContextualSiteGraphics/Logos/en_US/logos/bac-logo-v2.png",
    employer_website: "http://www.bankofamerica.com",
    employer_company_type: "Finance",
    job_publisher: "The Muse",
    job_employment_type: "FULLTIME",
    job_title: "Analyst, US Rates Trading, Global FICC, Japan",
    job_apply_link:
      "https://www.themuse.com/jobs/bankofamerica/analyst-us-rates-trading-global-ficc-japan",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5559,
    apply_options: [
      {
        publisher: "The Muse",
        apply_link:
          "https://www.themuse.com/jobs/bankofamerica/analyst-us-rates-trading-global-ficc-japan",
        is_direct: false,
      },
    ],
    job_description:
      "Job Description:\n\nAt Bank of America, we are guided by a common purpose to help make financial lives better through the power of every connection. Responsible Growth is how we run our company and how we deliver for our clients, teammates, communities and shareholders every day.\n\nOne of the keys to driving Responsible Growth is being a great place to work for our teammates around the world. We're devoted to being a diverse and inclusive workplace for everyone. We hire individuals with a broad range of backgrounds and experiences and invest heavily in our teammates and their families by offering competitive benefits to support their physical, emotional, and financial well-being.\n\nBank of America believes both in the importance of working together and offering flexibility to our employees. We use a multi-faceted approach for flexibility, depending on the various roles in our organization.\n\nWorking at Bank of America will give you a great career with opportunities to learn, grow and make an impact, along with the power to make a difference. Join us!\n\nJob Description:\n\nThis is a front office fixed income trading role on the US Rates team in Japan. You will be working in a dynamic and busy trading floor environment. You will be responsible for trading and hedging activities, and work as a team to assist in managing client orders and risk to formulate trading.\n\nResponsibilities:\n• Assist on Fixed Income trading and hedging activities for US Rates Trading (USTs and Swaps).\n• Assist in managing client orders and risk and to formulate trading\n• Help to originate, structure and model transactions\n• Work with broader team to develop and formulate trade ideas and develop new business\n• Assist in developing new products and bringing them to market\n• Assist in engineering spreadsheets for both sales and trading teams\n• Proactively assist in onboarding new counterparties, in conjunction with local contact point as well as regional Know Your Client teams.\n\nSkills:\n• Strong quantitative and analytical skills\n• Effective verbal and written communication\n• Comfortable with change and adjust to changing demands and requirements\n• Able to work under pressure\n• A strong team player and client focused\n• Demonstrates energy and drive\n• Creative thinking and problem-solving skills\n• Demonstrate a keen interest in the business",
    job_is_remote: false,
    job_posted_at_timestamp: 1713830398,
    job_posted_at_datetime_utc: "2024-04-22T23:59:58.000Z",
    job_city: null,
    job_state: null,
    job_country: "JP",
    job_latitude: 35.676422,
    job_longitude: 139.65002,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=japan&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=japan&htidocid=FSs0aq4qCHSmKmm_AAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {},
    job_job_title: "Analyst",
    job_posting_language: "en",
    job_onet_soc: "41303100",
    job_onet_job_zone: "3",
    job_occupational_categories: null,
    job_naics_code: "522110",
    job_naics_name: "Commercial Banking",
  },
  {
    job_id: "EOxDhSNajbrhvVz1AAAAAA==",
    employer_name: "Takeda Pharmaceutical",
    employer_logo:
      "https://www.takeda.com/4ab4e2/siteassets/system/top/howwework_logo_1600x900.jpg",
    employer_website: "http://www.takeda.com",
    employer_company_type: "Manufacturing",
    job_publisher: "Takeda Jobs",
    job_employment_type: "FULLTIME",
    job_title: "Head of Quality, New Plasma Facility Japan",
    job_apply_link:
      "https://jobs.takeda.com/job/juso-honmachi/head-of-quality-new-plasma-facility-japan/1113/64100658688",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.7356,
    apply_options: [
      {
        publisher: "Takeda Jobs",
        apply_link:
          "https://jobs.takeda.com/job/juso-honmachi/head-of-quality-new-plasma-facility-japan/1113/64100658688",
        is_direct: false,
      },
      {
        publisher: "Www.jp.takedajobs.com",
        apply_link:
          "https://www.jp.takedajobs.com/job/juso-honmachi/head-of-quality-new-plasma-facility-japan/5111/64100661104",
        is_direct: false,
      },
    ],
    job_description:
      "By clicking the “Apply” button, I understand that my employment application process with Takeda will commence and that the information I provide in my application will be processed in line with Takeda’s Privacy Notice and Terms of Use. I further attest that all information I submit in my employment application is true to the best of my knowledge.\n\nJob Description\n\nThe Head of Quality leads the Quality Organization, develops, and deploys the Quality Strategy and Quality Systems for the new plasma facility project, based on global Takeda and site Quality Standards.\n\nProvides leadership and oversight to all site Quality functions, and continuously develops people and teams.\n\nEnsures compliance and drives proactiveness and continuous improvement as well as quality culture of trust and speak up at the site.\n\nAs a member of the Quality Leadership Team, partners with all functions to achieve the site's & Business unit’s objectives.\n\nLocations\n\nOsaka (Juso), Japan\n\nWorker Type\n\nEmployee\n\nWorker Sub-Type\n\nFixed Term (Fixed Term)\n\nTime Type\n\nFull time",
    job_is_remote: false,
    job_posted_at_timestamp: 1713398400,
    job_posted_at_datetime_utc: "2024-04-18T00:00:00.000Z",
    job_city: "大阪市",
    job_state: null,
    job_country: "JP",
    job_latitude: 34.693726,
    job_longitude: 135.50226,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=japan&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=japan&htidocid=EOxDhSNajbrhvVz1AAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: false,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {},
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "11305100",
    job_onet_job_zone: "4",
    job_occupational_categories: null,
    job_naics_code: "325412",
    job_naics_name: "Pharmaceutical Preparation Manufacturing",
  },
  {
    job_id: "OUAijuB_M6FFXt2iAAAAAA==",
    employer_name: "confidential",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQO9GA3JrxOCnpJdTATLMQylB_XhGz6SSyfKFue&s=0",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "Daijob.com",
    job_employment_type: "FULLTIME",
    job_title: "Business Analyst - No Japanese Requirement!",
    job_apply_link: "https://www.daijob.com/en/jobs/detail/1340610",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6281,
    apply_options: [
      {
        publisher: "Daijob.com",
        apply_link: "https://www.daijob.com/en/jobs/detail/1340610",
        is_direct: false,
      },
    ],
    job_description:
      "Seeking a Business Analyst to support data governance initiatives, including retention and access projects, by understanding business needs, defining solutions, and collaborating with specialist teams.\n\n職務内容\n• Understand and document datasets and requirements.\n• Identify regulatory requirements for data retention or deletion.\n• Analyze and improve existing data management processes.\n• Document business and system requirements for data governance projects.\n• Collaborate with cross-functional teams to mitigate data risks and issues.\n\n理想の人材\n• 2-5 years of relevant business analysis experience.\n• Strong communication and negotiation skills.\n• Ability to work independently and in multicultural environments.\n• Problem-solving skills with a focus on risk assessment and mitigation.\n\n条件・待遇\n• Collaborative work environment with a focus on innovation and continuous learning.\n• Competitive compensation and benefits package.\n• Work with skillful people from all over the world.\n• 3 free meals at the cafeteria.\n• Shops, restaurants, cafes, and big parks nearby.\n\nTo apply online please click the 'Apply' button below. For a confidential discussion about this role please contact Naoko Toda at +81 3 6832 8648.",
    job_is_remote: false,
    job_posted_at_timestamp: 1713830400,
    job_posted_at_datetime_utc: "2024-04-23T00:00:00.000Z",
    job_city: null,
    job_state: null,
    job_country: "JP",
    job_latitude: 35.676422,
    job_longitude: 139.65002,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=japan&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=japan&htidocid=OUAijuB_M6FFXt2iAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-06-22T00:00:00.000Z",
    job_offer_expiration_timestamp: 1719014400,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 24,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: 6000000,
    job_max_salary: 8000000,
    job_salary_currency: "JPY",
    job_salary_period: "YEAR",
    job_highlights: {},
    job_job_title: "Business analyst",
    job_posting_language: "en",
    job_onet_soc: "13111100",
    job_onet_job_zone: "5",
    job_occupational_categories: null,
    job_naics_code: null,
    job_naics_name: null,
  },
  {
    job_id: "RxqTBugxsXJgaDC5AAAAAA==",
    employer_name: "Hilton",
    employer_logo: "https://www.hilton.com/modules/assets/svgs/logos/WW.svg",
    employer_website: "https://www.hilton.com/en/hilton",
    employer_company_type: "Accommodation",
    job_publisher: "Hilton Careers",
    job_employment_type: "FULLTIME",
    job_title:
      "Manager/Senior Manager, Projects & Design – Japan, Korea & Micronesia",
    job_apply_link:
      "https://jobs.hilton.com/apac/it/job/APA014CE/Manager-Senior-Manager-Projects-Design-Japan-Korea-Micronesia",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.8153,
    apply_options: [
      {
        publisher: "Hilton Careers",
        apply_link:
          "https://jobs.hilton.com/apac/it/job/APA014CE/Manager-Senior-Manager-Projects-Design-Japan-Korea-Micronesia",
        is_direct: false,
      },
      {
        publisher: "Hospitality Online",
        apply_link:
          "https://www.hospitalityonline.com/jobs/4038162-manager-senior-manager-projects-design-japan-korea-micronesia",
        is_direct: false,
      },
      {
        publisher: "Talentify",
        apply_link:
          "https://www.talentify.io/job/managersenior-manager-projects-and-design-japan-korea-and-micronesia-tokyo-tokyo-hilton-apa014ce",
        is_direct: false,
      },
    ],
    job_description:
      "## This position requires both JAPANESE and ENGLISH proficiency. ##\n\nThe Manager/Senior Manager, Projects & Design – Japan, Korea & Micronesia reports to the Senior Director, Projects & Design, and is responsible for the management of project stakeholders, project timeline, design process, and the successful opening/conversion/renovation of the hotel project. As the point of contact between Owners, and internal and external partners, you are a conduit of information, collaborator, and facilitator between Hilton and Ownership.\nYou will cover the Japan, Korea & Micronesia (JKM) region and be responsible for focus-service, full-service hotel projects across all Hilton brands.\n\nWhat will I be doing?\nAs the Manager/Senior Manager, Projects & Design – Japan, Korea & Micronesia, you will be responsible for performing the following tasks to the highest standards:\n\nProject Management\n• Providing technical services and guiding all elements of the planning and design phase of the project.\n• Support the Owner’s project timelines and construction progress to ensure a seamless hotel handover.\n• Providing mentorship for the implementation of brand standards and any recommendations for meeting brand standards.\n• Overseeing construction activities.\n• Reporting to Owners, Stakeholders, and Senior Director on findings, key dates, solving project risks that will affect the hotel's success and opening, and conditional and final approvals.\n• Improving the final product, and preparation of waiver requests.\n• Assisting in the solving of design problems as they arise in concert with Owners, Architects, Consultants, and Hilton Stakeholders.\n• Implement effective and efficient strategies to best suit the organization.\n• Plan meetings, agendas, site visits, and program deliverables optimally engaging/disengaging all parties promptly allowing for accurate preparation and planning for the attendees.\n• Plan meetings and travel in consideration of other Stakeholders and attendees' travel times and travel expense agreements for several trips.\n\nDesign & Development Support\n• Review and approval of architectural planning, interior design, and FF&E designs, in consultation with the Senior Director, to ensure they meet Brand standards and Brand equity.\n• Provides technical assistance to the Development team before application to facilitate project approval.\n• Contribute to country-specific addenda to global Brand standards for all Hilton brands.\n\nWhat are we looking for?\nA Manager/Senior Manager, Projects & Design – Japan, Korea & Micronesia serving Hilton Brands is always working on behalf of our Guests and working with other Team Members. To successfully fill this role, you should maintain the attitude, behaviors, skills, and values that follow:\n• Bachelor’s degree in architecture\n• Minimum of 7 years of experience in hospitality design roles and project management.\n• Excellent communication, presentation, written, and public speaking skills.\n• Proficient in English and Japanese.\n• Ability to lead change, resolve issues, and ensure collaboration within teams and/or units, including maintaining the highest standards of ethical conduct and integrity.\n• Ability to evaluate and find opportunities from a strategic perspective, develop, prioritize, and implement plans to meet the organization’s core strategic goals.\n• Proficient skills in Microsoft Office products. Understanding of the principles and practical application of the software.\nAbility to accurately estimate project duration and pre-empt potential pitfalls based on experience, scheduling analysis, and interaction with other stakeholders and ownership teams.\n• Ability to assimilate new concepts and practices into the position and the department. To provide subordinates with effective on-the-job training, policies and procedures, departmental training topics, and professional development.\n• Financial management and leadership skills, including the ability to monitor expenses against commitments, set priorities for funding, and develop annual financial goals.\n• Ability to travel when required.\n\nWhat will it be like to work for Hilton?\n\nHilton is the leading global hospitality company, spanning the lodging sector from luxurious full-service hotels and resorts to extended-stay suites and mid-priced hotels. For nearly a century, Hilton has offered business and leisure travelers the finest in accommodations, service, amenities and value. Hilton is dedicated to continuing its tradition of providing exceptional guest experiences across its global brands. Our vision “to fill the earth with the light and warmth of hospitality” unites us as a team to create remarkable hospitality experiences around the world every day. And, our amazing Team Members are at the heart of it all!",
    job_is_remote: false,
    job_posted_at_timestamp: 1713744000,
    job_posted_at_datetime_utc: "2024-04-22T00:00:00.000Z",
    job_city: "東京",
    job_state: null,
    job_country: "JP",
    job_latitude: 35.6804,
    job_longitude: 139.76901,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=japan&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=japan&htidocid=RxqTBugxsXJgaDC5AAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {},
    job_job_title: "Manager/senior manager",
    job_posting_language: "en",
    job_onet_soc: "11904100",
    job_onet_job_zone: "5",
    job_occupational_categories: ["Corporate"],
    job_naics_code: "7211",
    job_naics_name: "Traveler Accommodation",
  },
  {
    job_id: "-t04bG883KMJGU5uAAAAAA==",
    employer_name: "Bank of America",
    employer_logo:
      "https://www.bankofamerica.com/content/images/ContextualSiteGraphics/Logos/en_US/logos/bac-logo-v2.png",
    employer_website: "http://www.bankofamerica.com",
    employer_company_type: "Finance",
    job_publisher: "Bank Of America Careers Site",
    job_employment_type: "FULLTIME",
    job_title:
      "Assistant Vice President - Operations Consultant – Credit Operations",
    job_apply_link:
      "https://careers.bankofamerica.com/en-us/job-detail/24014878/assistant-vice-president-operations-consultant-credit-operations-tokyo-japan",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.7968,
    apply_options: [
      {
        publisher: "Bank Of America Careers Site",
        apply_link:
          "https://careers.bankofamerica.com/en-us/job-detail/24014878/assistant-vice-president-operations-consultant-credit-operations-tokyo-japan",
        is_direct: false,
      },
      {
        publisher: "Finance Jobs - Accounting & Financial Women's Alliance",
        apply_link:
          "https://jobs.afwa.org/job/assistant-vice-president-operations-consultant-credit-operations/73200372/",
        is_direct: false,
      },
      {
        publisher: "Phi Beta Lambda (FBLA-PBL)",
        apply_link:
          "https://fbla-pbl-jobs.careerwebsite.com/job/assistant-vice-president-operations-consultant-credit-operations/73200372/",
        is_direct: false,
      },
    ],
    job_description:
      "Job Description:\n\nAbout Bank of America:\n\nOur purpose as a firm is to make financial lives better, through the power of every connection. Across the world, we partner with leading corporate and institutional investors through our offices in more than 40 countries. In the U.S alone, we serve almost all Fortune 500 companies and approximately 59 million consumers and small-business customers. We provide a full suite of financial products and services, from banking and investments to asset and risk management. We cover a broad range of asset classes, making us a global leader in corporate and investment banking, sales and trading.\n\nConnecting Asia Pacific to the World\n\nOur Asia Pacific team is spread across 23 offices in 12 markets. We are focused on connecting Asia to the world and the world to Asia, using our global expertise to ensure success is shared between us, our clients and our communities. Our regional footprint covers 12 currencies, more than a dozen languages and five time zones, placing us firmly among the region’s leading financial services companies.\n\nBank of America is committed to attracting, recruiting and retaining top diverse talent from across the globe. Our diversity and inclusion mission is to actively promote an inclusive work environment where all employees have the opportunity to achieve personal success and contribute to the growth of our business. Each of our global Employee Networks bring together employees, create dialogue and awareness in support of our Diversity and Inclusion.\n\nPosition Description\n\nThis role as Operations Consultant under Credit Operations is responsible for the day-to-day operations of loan administration operations to ensure first class client experience for our clients.\n\nKey Responsibilities\n• Work closely with Corporate Banking Sales and Credit Officers to close and execute Tokyo Branch-booked loans and commitment facilities. Liaise with Finance, Treasury, Agency and Leasing teams, both locally and globally for the booking processes of loan products. Manage disbursement and renewal of loans as loan administrator for external stakeholders such as borrowers and agent banks.\n• Manage Credit Documentation Files for Tokyo Branch. Day-to-day tasks including verification of signatures, distribution of relevant documents to the involved teams/lines of businesses, preparation of checklists, and to ensure files are reviewed by Credit Officers.\n• Ensure all transactions are accurately processed by the Bank’s process servicing center in India, while ensuring branch-oriented information is shared timely and accurately with the relevant processing teams.\n• Ensure timely reconciliation and review of reports.\n• Prepare regulatory reports regarding loans and credits. Ensure credit and loan-related data are appropriately reported accurately and consistently as well as being compliant with the reporting guidelines.\n• Maintain the expected quality standards to ensure client’s needs are met, and continued effort is made to exceed the client’s expectations.\n• Understand the risks associated with the Products and its related processes. Ensure risks are identified and minimized.\n• Lead or participate in internal initiatives/projects representing the voice of the business, taking ownership, and delivering the execution of these projects.\n• Demonstrate key attributes for success including ability to pay attention to detail, being a team player, take end-to-end ownership, drive results to grow the business, as well as sustaining intensity and optimism while focusing on the client.\n\nKey Requirements\n• At least 5 years’ working experience in banking industry. Cross-border loan related working experience is preferred.\n• Knowledge of overall banking products and documents.\n• Knowledge of loan administration – review and understand loan agreements / structure of loan regarding operational matters, cash-flow, and funding arrangements, etc.\n• Ability to quickly absorb and follow policies and procedures, demonstrate ability to continuously learn and adapt with a proactive work ethic.\n• Communication and interpersonal skills – ability to work with our clients and business partners, to positively influence people, to handle difficult conversations, and to be a good team player.\n• Organization skills – ability to manage workload and prioritize tasks to support business and clients as well as ability to work under pressure and achieve goals.\n• Critical thinking skills – ability to assess quantitative and qualitative data to identify key themes that require deeper analysis and assessment.\n• Problem solving skills – ability to understand issues and provide solutions, to look at a problem from a new perspective and to develop/share new ideas.\n• Integrity – attitude to do the right thing for the bank and its clients as well as ability to escalate potential issues to senior management timely.\n• Flexible and adaptable to change. Strong commitment with positive and proactive attitude towards challenge.\n• Ability to communicate fluently with internal and external stakeholders in Japanese and English, both orally and written.\n• General PC, Windows, Microsoft Office knowledge (Excel, Word, PowerPoint).\n\nBank of America is an equal opportunities employer.",
    job_is_remote: false,
    job_posted_at_timestamp: 1713484800,
    job_posted_at_datetime_utc: "2024-04-19T00:00:00.000Z",
    job_city: "東京",
    job_state: null,
    job_country: "JP",
    job_latitude: 35.6804,
    job_longitude: 139.76901,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=japan&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=japan&htidocid=-t04bG883KMJGU5uAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 60,
      experience_mentioned: true,
      experience_preferred: true,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {},
    job_job_title: "Vice president",
    job_posting_language: "en",
    job_onet_soc: "13207100",
    job_onet_job_zone: "4",
    job_occupational_categories: null,
    job_naics_code: "522110",
    job_naics_name: "Commercial Banking",
  },
  {
    job_id: "nxgZFgKkH9GOAOEhAAAAAA==",
    employer_name: "Applus IDIADA",
    employer_logo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Applus%2B_IDIADA_Logo.svg/320px-Applus%2B_IDIADA_Logo.svg.png",
    employer_website: "http://www.applusidiada.com",
    employer_company_type: "Computer Services",
    job_publisher: "Smart Recruiters Jobs",
    job_employment_type: "FULLTIME",
    job_title: "Account Manager - Japan",
    job_apply_link:
      "https://jobs.smartrecruiters.com/ApplusIDIADA1/743999982273017-account-manager-japan",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6322,
    apply_options: [
      {
        publisher: "Smart Recruiters Jobs",
        apply_link:
          "https://jobs.smartrecruiters.com/ApplusIDIADA1/743999982273017-account-manager-japan",
        is_direct: false,
      },
      {
        publisher: "BeBee 日本",
        apply_link: "https://jp.bebee.com/job/79aaa6af71f8bd60f8510936367c5924",
        is_direct: false,
      },
    ],
    job_description:
      "Company Description\n\nApplus IDIADA is a young and dynamic organization that values participation, collaboration and long-term relationships. We continuously generate professional development opportunities and growth alternatives for motivated and engaged professionals.\n\nJob Description\n\nMISSION\n\nAs a member of the international Sales and Client Management of the IDIADA group, you will be in charge of developing our relationship with our clients in the automotive sector in Japan (vehicle and system/component manufacturers).\n\nRESPONSIBILITIES\n• Keep and increase existing contacts within the automotive industry, aiming at detecting project opportunities with special emphasis on forging long-term trusting relationships.\n• To make a market investigation, canvass operations, reply to clients' requests for quotations, push and follow up on offers and conduct project negotiations with the support of the sales team and the Product / Project Managers from our headquarters.\n\nQualifications\n\nJunior profile recently graduated from the University, engineering or technical sciences will be preferred but is not a must.\n• Good communication skills and confidence in discussions at different hierarchical levels.\n• Ability to convince through technical arguments and to express to the client the points of common interest focused on finding the most suitable aspects for both sides.\n• Goal-driven with strong customer and service orientation.\n• Open to working in a very international company with multicultural teams.\n• Willingness to travel at an international level.\n\nEducation\n\n- University Degree.\n\nLanguages\n\n- Native Japanese.\n\n- Fluent in English.\n\n- Spanish is a plus\n\nAdditional Information\n\nApplus IDIADA is committed to diversity and inclusion. We don’t put limits on you, so don’t put limits on yourself either. There is a place for everyone.",
    job_is_remote: false,
    job_posted_at_timestamp: 1713777015,
    job_posted_at_datetime_utc: "2024-04-22T09:10:15.000Z",
    job_city: "東京",
    job_state: null,
    job_country: "JP",
    job_latitude: 35.6804,
    job_longitude: 139.76901,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=japan&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=japan&htidocid=nxgZFgKkH9GOAOEhAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: false,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: true,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {},
    job_job_title: "Account manager",
    job_posting_language: "en",
    job_onet_soc: "41401300",
    job_onet_job_zone: null,
    job_occupational_categories: null,
    job_naics_code: "541511",
    job_naics_name: "Custom Computer Programming Services",
  },
  {
    job_id: "UecEkED1lvLSfvptAAAAAA==",
    employer_name: "ABB",
    employer_logo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/ABB_logo.svg/2560px-ABB_logo.svg.png",
    employer_website: "http://www.abb.com",
    employer_company_type: "Manufacturing",
    job_publisher: "ABB Career",
    job_employment_type: "FULLTIME",
    job_title: "アソシエイトプロジェクトマネージャー",
    job_apply_link:
      "https://careers.abb/global/en/job/91119891/%E3%82%A2%E3%82%BD%E3%82%B7%E3%82%A8%E3%82%A4%E3%83%88%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%83%9E%E3%83%8D%E3%83%BC%E3%82%B8%E3%83%A3%E3%83%BC",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.7137,
    apply_options: [
      {
        publisher: "ABB Career",
        apply_link:
          "https://careers.abb/global/en/job/91119891/%E3%82%A2%E3%82%BD%E3%82%B7%E3%82%A8%E3%82%A4%E3%83%88%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%83%9E%E3%83%8D%E3%83%BC%E3%82%B8%E3%83%A3%E3%83%BC",
        is_direct: false,
      },
      {
        publisher: "LinkedIn",
        apply_link:
          "https://jp.linkedin.com/jobs/view/%E3%82%A2%E3%82%BD%E3%82%B7%E3%82%A8%E3%82%A4%E3%83%88%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%83%9E%E3%83%8D%E3%83%BC%E3%82%B8%E3%83%A3%E3%83%BC-at-abb-3907791874",
        is_direct: false,
      },
    ],
    job_description:
      "アソシエイトプロジェクトマネージャー\nより生産的で持続可能な未来を実現するために、社会と産業の変革に活力を与え ている我々のグローバルチームとともに、ABBで次のキャリアステップを踏み出 してみませんか。\nABBでは、性別、LGBTQ+、能力、民族、世代など、あらゆる次元で多様性とイン クルージョンを推進するという明確な目標を掲げています。私たちは、一人ひと りが個人的にも集団としても、個人の違いを歓迎し、それを称える旅に乗り出し ています。\n\nロボティクス＆ディスクリート・オートメーション事業本部のアソシエイトプロジェクトマネージャーとして、塗装システムプロジェクトの実行を主導し、関連するすべての活動が会社の手順、契約仕様、品質基準、健康、安全および環境要件、コスト/収益性目標、およびスケジュール目標に従って実行される事に責任を持ち、一部アフターサービスも対応します。\n\n法人はABB株式会社です。\n現在の職務\n• プロジェクトのリーダーシップ\n• -プロジェクトに割り当てられたプロジェクト チームをリードします。\n• -すべてのタスクとマイルストーンを達成するために、社内および社外のリソースを動機付け、監視します。\n• -プロジェクトに取り組んでいる割り当てられたリソースに関するパフォーマンス フィードバックを提供します。\n• 指示とガイドライン\n• -標準的な ABB 内部指令と手順、関連するサイバー セキュリティ規制、標準、および契約上の要件への準拠を保証します。\n• プロジェクトの実行と管理\n• -プロジェクトが実行のベスト プラクティスと ABB ポリシーに従っていることを確認します。\n• -プロジェクトの進行状況とリソースの効率的な利用を効果的に監視および制御します。\n• -プロジェクトの財務を監視および管理し、プロジェクトの請求ステータス、コスト、経費、およびキャッシュ フローを監督します。\n• -プロジェクトのリスクを特定、評価、定量化、管理し、すべての機会が特定され追求されるようにします。\n• -プロジェクト全体を通じて学んだ教訓を収集、分析、共有します。\n• -プロジェクトの正式な承認、契約の完了、顧客による承認をすべて契約に従って推進します。\n• 契約とクレーム/調達管理\n• -ABB ポリシーと契約合意に従って、プロジェクトが契約と請求管理を一貫して適用することを保証します。\n• -サプライチェーン管理と連携し、プロジェクトに必要なサービス、資材、設備を外部および内部のサプライヤーから適切に調達します。\n• -サプライヤーとの交渉、クレーム、プロジェクト変更における調達と物流をサポートします。\n• ステークホルダーとの関係\n• -顧客の主要な連絡先として、またプロジェクトの問題のエスカレーション ポイントとして機能します。\n• -社内外の利害関係者との強力な関係を構築および維持し、すべての利害関係者と効果的にコミュニケーションします。\n• 健康、安全、環境 (HSE)\n• -プロジェクトが会社の健康、安全、環境ポリシーに従っていることを確認します。\n• -プロジェクトの HSE 計画を作成し、コラボレーション/コンソーシアム パートナーやサブサプライヤーを含むすべての利害関係者とプロジェクト全体で共通の HSE ポリシーとレポートが実装されていることを確認します。\n• -現場の安全をサポートし、一貫した HSE パフォーマンスを保証するための独自のアクション/取り組みを実証します。\n• プロジェクトの回復\n• -必要に応じてガイダンスやコーチングを受けて、スケジュールの遅延やコストの超過に対して即座に回復措置を適用します。\n• 計画とスケジュール設定\n• -基本的なプロジェクト スケジューリング手法を定義および適用して、スケジュール リスクをプロアクティブに管理し、OTD の影響による将来のスケジュールの逸脱の可能性を回避します。\n• -作業パッケージをアクティビティに分割し、プロジェクト作業の見積もり、スケジュール、実行、監視、制御の基礎を提供し、範囲、コスト、リソースの制約に基づいてプロジェクトのスケジュールを作成します。\n• -プロジェクトのスケジュールを管理し、すべてのエンジニアリング、調達、製造、テスト、現場作業、その他の活動の進捗状況を継続的に監視および文書化するためのスケジュールのベースラインを確立します。\n• -進捗状況を追跡し、プロジェクトの変更や作業の進捗状況を反映するために定期的にスケジュールを更新し、現地のガイドラインに従って逸脱をエスカレーションします。\n• -クリティカル パス理論の理解を示し、その目的と機能を計算して説明できる。\n• 文書管理\n• 契約上の作業範囲で必要とされるすべての文書成果物を特定して計画し、この計画をプロジェクト全体の計画/スケジュールに組み込みます。\n• -文書の進捗状況を追跡し、顧客からの期限を過ぎたコメントをフォローアップします。\n\n経歴\n• 日本語能力試験１級レベルの日本語力\n• 基本的な機械的および電気的知識\n• 建築、機械、プラントのプロジェクトマネージャー経験（現場管理経験）\n• AUTO CADの使用経験がる方（機械設計経験がある方）\n• 製品サービス機能での 5 年以上の実務経験が望ましい\n• B to B サービスおよびサポートの経験者優遇\n• 顧客アカウント管理の経験が望ましい\n• 英語に抵抗が無い方\n• 土日、長期連休含む出勤や出張が可能な方\n\n福利厚生\n• 退職金制度\n• 生命保険\n• 柔軟な働き方の実現\n• 有給育児休暇 (性別区別なし)\n• 交通費手当\n当社について\n\nご応募をお待ちしております（書類は英語も合わせてご提出ください）。ABBに ついてもっと知りたい方は、弊社のウェブサイト www.abb.com をご覧ください 。",
    job_is_remote: false,
    job_posted_at_timestamp: 1713830400,
    job_posted_at_datetime_utc: "2024-04-23T00:00:00.000Z",
    job_city: "品川区",
    job_state: null,
    job_country: "JP",
    job_latitude: 35.609196,
    job_longitude: 139.73033,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=japan&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=japan&htidocid=UecEkED1lvLSfvptAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: false,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {},
    job_job_title: null,
    job_posting_language: "ja",
    job_onet_soc: null,
    job_onet_job_zone: null,
    job_occupational_categories: ["Project Management"],
    job_naics_code: "335311",
    job_naics_name:
      "Power, Distribution, and Specialty Transformer Manufacturing",
  },
];
